"""Sample data generation and loading helpers for openscout.

Everything generated by the ``synthetic_*`` functions in this module is
**fabricated**: random numbers dressed up with generic labels like
"Player A" and "Team X". None of it refers to any real athlete, team, or
historical game. It exists purely so the CLI's ``demo`` command and the
test suite have realistic-shaped input to run metrics against.

This module also provides small, dependency-free loaders (``load_json``,
``load_csv``) for pointing openscout at your own real data files.
"""

from __future__ import annotations

import csv
import json
import random
from pathlib import Path
from typing import Any

PathLike = str | Path


# --- synthetic basketball data ----------------------------------------------

def synthetic_basketball_boxscore(seed: int | None = None) -> dict[str, Any]:
    """Generate one fabricated basketball box score for "Player A".

    All numbers are randomly generated within plausible ranges purely for
    demo/testing purposes -- they do not describe any real player or game.
    """
    rng = random.Random(seed)
    fga = rng.randint(8, 22)
    fg = rng.randint(0, fga)
    fg3a = rng.randint(0, min(10, fga))
    fg3 = rng.randint(0, fg3a)
    fta = rng.randint(0, 10)
    ft = rng.randint(0, fta)
    pts = 2 * (fg - fg3) + 3 * fg3 + ft

    return {
        "player": "Player A",
        "pts": float(pts),
        "fg": float(fg),
        "fga": float(fga),
        "fg3": float(fg3),
        "fg3a": float(fg3a),
        "ft": float(ft),
        "fta": float(fta),
        "orb": float(rng.randint(0, 5)),
        "drb": float(rng.randint(0, 8)),
        "ast": float(rng.randint(0, 10)),
        "stl": float(rng.randint(0, 4)),
        "blk": float(rng.randint(0, 3)),
        "tov": float(rng.randint(0, 5)),
        "pf": float(rng.randint(0, 5)),
        "min": float(rng.randint(15, 40)),
        # Opponent defensive rebounds, needed for the Four Factors' ORB%.
        "opp_drb": float(rng.randint(10, 35)),
    }


def synthetic_basketball_game(seed: int | None = None) -> list[dict[str, Any]]:
    """Generate a fabricated 5-player box score for "Team X" vs "Team Y"."""
    rng = random.Random(seed)
    boxes = []
    for label in "ABCDE":
        box = synthetic_basketball_boxscore(seed=rng.randint(0, 1_000_000))
        box["player"] = f"Player {label}"
        boxes.append(box)
    return boxes


# --- synthetic soccer data ---------------------------------------------------

_BODY_PARTS = ("foot", "foot", "foot", "head", "other")
_SITUATIONS = ("open_play", "open_play", "open_play", "set_piece", "counter")


def synthetic_soccer_shots(n: int = 5, seed: int | None = None) -> list[dict[str, Any]]:
    """Generate ``n`` fabricated shots for "Team X" for the toy xG model."""
    rng = random.Random(seed)
    shots = []
    for _ in range(n):
        shots.append(
            {
                "team": "Team X",
                "player": "Player A",
                "distance": round(rng.uniform(4.0, 30.0), 1),
                "angle": round(rng.uniform(10.0, 150.0), 1),
                "body_part": rng.choice(_BODY_PARTS),
                "situation": rng.choice(_SITUATIONS),
            }
        )
    return shots


def synthetic_soccer_passes(n: int = 10, seed: int | None = None) -> list[dict[str, Any]]:
    """Generate ``n`` fabricated passes/carries for the pass_pct / xt_added metrics."""
    rng = random.Random(seed)
    passes = []
    for _ in range(n):
        start_x = rng.uniform(0, 90)
        start_y = rng.uniform(0, 100)
        passes.append(
            {
                "team": "Team X",
                "from_player": "Player A",
                "to_player": "Player B",
                "start_x": round(start_x, 1),
                "start_y": round(start_y, 1),
                "end_x": round(min(100.0, start_x + rng.uniform(-10, 30)), 1),
                "end_y": round(min(100.0, max(0.0, start_y + rng.uniform(-20, 20))), 1),
                "completed": rng.random() > 0.2,
            }
        )
    return passes


# --- generic loaders ---------------------------------------------------------

def load_json(path: PathLike) -> Any:
    """Load a JSON file (a dict or a list of dicts) from disk."""
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def load_csv(path: PathLike) -> list[dict[str, Any]]:
    """Load a CSV file into a list of dicts, coercing numeric-looking fields to float."""
    with open(path, encoding="utf-8", newline="") as fh:
        reader = csv.DictReader(fh)
        rows = []
        for raw_row in reader:
            row: dict[str, Any] = {}
            for key, value in raw_row.items():
                if value is None:
                    continue
                row[key] = _coerce(value)
            rows.append(row)
        return rows


def _coerce(value: str) -> Any:
    stripped = value.strip()
    if stripped.lower() in {"true", "false"}:
        return stripped.lower() == "true"
    try:
        return float(stripped) if "." in stripped else int(stripped)
    except ValueError:
        return stripped


def load_input(path: PathLike) -> Any:
    """Load user-supplied data from ``path``, dispatching on file extension."""
    suffix = Path(path).suffix.lower()
    if suffix == ".json":
        return load_json(path)
    if suffix == ".csv":
        return load_csv(path)
    raise ValueError(f"unsupported input file type {suffix!r} (expected .json or .csv)")
